dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.6"
branches:
  only:
   - master
global:
  - PGPORT=5432
before_script:
  - cp local_settings.travis.py local_settings.py
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database decide owner decide"
  - python manage.py migrate
language: python
python:
  - "2.7"
  - "3.6"
env:
  - DJANGO=2.0 DB=postgres
  - DJANGO=1.11 DB=postgres
matrix:
 exlude:
  - python: "2.7"
    env: DJANGO=1.11 DB=postgres
  - python: "3.6"
    env: DJANGO=2.0 DB=postgres
before_install:
  - cd decide
install:
  - pip install -q Django==$DJANGO
  - pip install -r ../requirements.txt
script:
  - python manage.py test
